version: '3'

services:
  nginx:
    ports:
      - "8808:80"

  db:
    build: .docker/database
    restart: unless-stopped
    ports:
      - "3356:3306"
    volumes:
      - "$DB_DATA_PATH:/var/lib/mysql"
    env_file:
      - .env
    networks:
      - quiz-system
  
  # elasticsearch:
  #   build: .docker/elasticsearch
  #   environment:
  #     - discovery.type=single-node
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   ports:
  #     - "9200:9200"
  #   volumes:
  #     - ./esdata:/usr/share/elasticsearch/data
  #   networks:
  #     - quiz-system
