version: '3'

services:
  nginx:
    ports:
      - "8808:80"
    depends_on:
      - elasticsearch

  db:
    build: .docker/database
    restart: unless-stopped
    ports:
      - "3356:3306"
    volumes:
      - "$DB_DATA_PATH:/var/lib/mysql"
    env_file:
      - .env
    networks:
      - quiz-system
  
  elasticsearch:
    image: blacktop/elasticsearch:7.10
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    networks:
      - quiz-system
    
  # kibana:
  #   image: blacktop/kibana:7.6
  #   container_name: kibana
  #   hostname: kibana
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  #   ports:
  #     - "5601:5601"
  #   depends_on:
  #     - elasticsearch
  #   networks:
  #   - quiz-system
